"use server";

// ─── Store Template — server actions ────────────────────────────────────
//
// apply  — write branding + theme + blocks (source="template") from a
//          built-in or imported StoreTemplate.
// import — validate a JSON payload and apply it through the same pipe.
// export — serialise the current store into a Nexora template payload
//          that can be re-imported deterministically.
//
// Compatibility contract:
//   · We never delete blocks authored by the merchant (`source="manual"`)
//     or generated by the AI studio (`source="ai"`). Re-applying a
//     template only replaces rows with `source="template"`.
//   · All block shapes are validated against the existing renderer's
//     switch cases via validateBlockSettings + our own template schema.
//   · StoreBranding / StoreTheme are upserted; no schema migration.
//
// Editability contract:
//   · Every written row lands in StoreBlock / StoreBranding / StoreTheme,
//     which are already the canonical editing surfaces of /admin/store
//     and /admin/store?tab=branding. Nothing locks the merchant out.

import { revalidatePath } from "next/cache";

import { prisma } from "@/lib/db/prisma";
import { getAdminStoreId } from "@/lib/store-engine/actions";
import { validateBlockSettings } from "@/lib/store-engine/blocks/defaults";
import { getStoreProducts, getStoreCollections } from "@/lib/store-engine/catalog/queries";

import { findTemplateById } from "./templates";
import { parseTemplatePayload } from "./validation";
import { TEMPLATE_APPLY_EVENT_TYPE } from "./queries";
import type { StoreTemplate, StoreTemplateExport, TemplateBlock } from "@/types/store-templates";
import type { BlockType } from "@/types/store-engine";

export interface ApplyTemplateResult {
  ok: boolean;
  templateId?: string;
  blocksCreated?: number;
  errors?: string[];
}

// ─── Helpers ────────────────────────────────────────────────────────────

/** Build a fresh copy of a template's homeBlocks with real product /
 *  collection handles pulled from the store, so featured_* blocks work
 *  immediately even on templates shipped with empty handle arrays. We
 *  keep the first 6 items of each; merchants edit the selection later
 *  from /admin/store?tab=home. */
async function hydrateFeaturedHandles(
  storeId: string,
  blocks: readonly TemplateBlock[],
): Promise<TemplateBlock[]> {
  const needsProducts = blocks.some((b) => b.blockType === "featured_products" && !(b.settings.productHandles as unknown[] | undefined)?.length);
  const needsCollections = blocks.some((b) => b.blockType === "featured_categories" && !(b.settings.collectionHandles as unknown[] | undefined)?.length);

  const [products, collections] = await Promise.all([
    needsProducts ? getStoreProducts(storeId) : Promise.resolve([]),
    needsCollections ? getStoreCollections(storeId) : Promise.resolve([]),
  ]);

  const productHandles = products.slice(0, 6).map((p) => p.handle).filter((h): h is string => typeof h === "string" && h.length > 0);
  const collectionHandles = collections.slice(0, 6).map((c) => c.handle).filter((h): h is string => typeof h === "string" && h.length > 0);

  return blocks.map((block) => {
    if (block.blockType === "featured_products" && !(block.settings.productHandles as unknown[] | undefined)?.length) {
      return { ...block, settings: { ...block.settings, productHandles } };
    }
    if (block.blockType === "featured_categories" && !(block.settings.collectionHandles as unknown[] | undefined)?.length) {
      return { ...block, settings: { ...block.settings, collectionHandles } };
    }
    return block;
  });
}

/** Core apply routine shared by every entrypoint (built-in id, raw JSON
 *  import, export re-import). Non-exported on purpose. */
async function applyTemplateCore(
  storeId: string,
  template: StoreTemplate,
): Promise<ApplyTemplateResult> {
  // 1. Settings validation: every block's settings must pass the same
  //    rules the existing storefront enforces. If a template ships an
  //    invalid settings object, fail loudly — we don't silently drop it.
  const validationErrors: string[] = [];
  template.homeBlocks.forEach((block, idx) => {
    const { valid, errors } = validateBlockSettings(block.blockType as BlockType, block.settings);
    if (!valid) {
      validationErrors.push(...errors.map((e) => `homeBlocks[${idx}] (${block.blockType}): ${e}`));
    }
  });
  if (validationErrors.length > 0) {
    return { ok: false, errors: validationErrors };
  }

  // 2. Hydrate featured_products / featured_categories with live handles.
  const hydrated = await hydrateFeaturedHandles(storeId, template.homeBlocks);

  // 3. Resolve store slug for route-aware defaults (hero primaryActionLink).
  const store = await prisma.store.findUnique({
    where: { id: storeId },
    select: { slug: true },
  });
  const slug = store?.slug ?? "";

  // 4. Transaction: branding + theme + blocks + optional navigation + event.
  await prisma.$transaction(async (tx) => {
    await tx.storeBranding.upsert({
      where: { storeId },
      update: {
        primaryColor: template.branding.primaryColor,
        secondaryColor: template.branding.secondaryColor,
        fontFamily: template.branding.fontFamily,
        tone: template.branding.tone,
      },
      create: {
        storeId,
        primaryColor: template.branding.primaryColor,
        secondaryColor: template.branding.secondaryColor,
        fontFamily: template.branding.fontFamily,
        tone: template.branding.tone,
      },
    });

    await tx.storeTheme.upsert({
      where: { storeId },
      update: { activeTheme: template.themeStyle, themeStatus: "draft" },
      create: { storeId, activeTheme: template.themeStyle, themeStatus: "draft", isPublished: false },
    });

    // Replace ONLY template-sourced blocks for this page. Manual blocks
    // and AI-sourced blocks stay intact. This preserves any work the
    // merchant did on top of a previous template.
    await tx.storeBlock.deleteMany({ where: { storeId, pageType: "home", source: "template" } });

    const rowsToCreate = hydrated.map((block, idx) => {
      // Backfill empty primaryActionLink in hero with the store's
      // products page so the CTA never deep-links to a dead URL.
      const settings: Record<string, unknown> = { ...block.settings };
      if (block.blockType === "hero" && (!settings.primaryActionLink || settings.primaryActionLink === "") && slug) {
        settings.primaryActionLink = `/store/${slug}/products`;
      }
      return {
        storeId,
        pageType: "home",
        blockType: block.blockType,
        sortOrder: idx,
        isVisible: block.isVisible ?? true,
        settingsJson: JSON.stringify(settings),
        source: "template",
        state: "draft",
      };
    });

    if (rowsToCreate.length > 0) {
      await tx.storeBlock.createMany({ data: rowsToCreate });
    }

    // Footer navigation — only if the template declared groups. We
    // replace same-group rows to avoid duplicates, but leave other
    // groups the merchant might have (e.g. custom "Recursos").
    if (template.footerNavigation && template.footerNavigation.length > 0) {
      for (const group of template.footerNavigation) {
        await tx.storeNavigation.deleteMany({ where: { storeId, group: group.group } });
        const rows = group.items.map((item, idx) => ({
          storeId,
          group: group.group,
          label: item.label,
          href: item.href,
          sortOrder: idx,
          isVisible: true,
        }));
        if (rows.length > 0) {
          await tx.storeNavigation.createMany({ data: rows });
        }
      }
    }

    // Audit event — also drives the "tema actual" chip via the
    // metadataJson.templateId field.
    await tx.systemEvent.create({
      data: {
        storeId,
        entityType: "store",
        entityId: storeId,
        eventType: TEMPLATE_APPLY_EVENT_TYPE,
        severity: "info",
        source: "store_template",
        message: `Template "${template.name}" aplicado como base editable.`,
        metadataJson: JSON.stringify({ templateId: template.id, themeStyle: template.themeStyle }),
      },
    });
  });

  revalidatePath("/admin/store-ai");
  revalidatePath("/admin/store-ai/themes");
  revalidatePath("/admin/store");
  if (slug) {
    revalidatePath(`/store/${slug}`);
  }

  return { ok: true, templateId: template.id, blocksCreated: hydrated.length };
}

// ─── Entry points ───────────────────────────────────────────────────────

export async function applyBuiltInTemplateAction(templateId: string): Promise<ApplyTemplateResult> {
  const storeId = await getAdminStoreId();
  if (!storeId) return { ok: false, errors: ["Sesión inválida o tienda no encontrada."] };

  const template = findTemplateById(templateId);
  if (!template) {
    return { ok: false, errors: [`Template "${templateId}" no existe en el registro integrado.`] };
  }
  return applyTemplateCore(storeId, template);
}

export async function applyImportedTemplateAction(rawJson: string): Promise<ApplyTemplateResult> {
  const storeId = await getAdminStoreId();
  if (!storeId) return { ok: false, errors: ["Sesión inválida o tienda no encontrada."] };

  const parsed = parseTemplatePayload(rawJson);
  if (!parsed.ok || !parsed.value) {
    return { ok: false, errors: parsed.errors };
  }
  return applyTemplateCore(storeId, parsed.value);
}

export async function exportCurrentStoreAsTemplateAction(): Promise<
  { ok: true; payload: StoreTemplateExport } | { ok: false; errors: string[] }
> {
  const storeId = await getAdminStoreId();
  if (!storeId) return { ok: false, errors: ["Sesión inválida o tienda no encontrada."] };

  const [store, branding, theme, blocks, navRows] = await Promise.all([
    prisma.store.findUnique({ where: { id: storeId }, select: { name: true } }),
    prisma.storeBranding.findUnique({ where: { storeId } }),
    prisma.storeTheme.findUnique({ where: { storeId } }),
    prisma.storeBlock.findMany({
      where: { storeId, pageType: "home", isVisible: true },
      orderBy: { sortOrder: "asc" },
    }),
    prisma.storeNavigation.findMany({
      where: { storeId, group: { in: ["footer_shop", "footer_support"] } },
      orderBy: [{ group: "asc" }, { sortOrder: "asc" }],
    }),
  ]);

  if (!store) return { ok: false, errors: ["Tienda no encontrada."] };

  // Group nav items back into TemplateNavGroup shape.
  const navByGroup = new Map<string, { label: string; href: string }[]>();
  for (const row of navRows) {
    const bag = navByGroup.get(row.group) ?? [];
    bag.push({ label: row.label, href: row.href });
    navByGroup.set(row.group, bag);
  }

  const homeBlocks: TemplateBlock[] = blocks.map((b) => {
    let settings: Record<string, unknown> = {};
    try {
      settings = JSON.parse(b.settingsJson);
    } catch {
      settings = {};
    }
    return {
      blockType: b.blockType as TemplateBlock["blockType"],
      settings,
      isVisible: b.isVisible,
    };
  });

  const source: StoreTemplate = {
    id: `exported-${storeId.slice(0, 8)}`,
    name: `${store.name} — exportado`,
    description: "Template exportado desde la tienda actual. Editable y re-importable en cualquier tienda Nexora.",
    industry: "Personalizado",
    themeStyle: (theme?.activeTheme as StoreTemplate["themeStyle"]) ?? "minimal",
    branding: {
      primaryColor: branding?.primaryColor ?? "#111111",
      secondaryColor: branding?.secondaryColor ?? "#F4F4F5",
      fontFamily: branding?.fontFamily ?? "Inter",
      tone: branding?.tone ?? "Neutro",
    },
    homeBlocks,
    footerNavigation: Array.from(navByGroup.entries()).map(([group, items]) => ({ group, items })),
    version: 1,
  };

  const payload: StoreTemplateExport = {
    kind: "nexora.store-template",
    exportedAt: new Date().toISOString(),
    source,
  };

  return { ok: true, payload };
}
