// ─── Theme Presets — Non-destructive token overrides ─────────────────────────
//
// Each preset modifies ONLY tokens. It never destroys sections, blocks, or
// navigation. Presets are reversible: applying a different preset (or resetting
// to defaults) restores the previous state.

import type { ThemePreset, ThemeTokens } from "./types";

export const THEME_PRESETS: readonly ThemePreset[] = [
  {
    id: "minimal",
    name: "Minimal",
    description: "Espacios amplios, colores neutros, tipografía limpia.",
    variant: "light",
    tokens: {
      colors: {
        primary: "#0F172A",
        secondary: "#F1F5F9",
        accent: "#3f4f9a",
        background: "#ffffff",
        surface: "#f8fafc",
        text: "#0f172a",
        muted: "#64748b",
        border: "rgba(15, 23, 42, 0.08)",
        success: "#15956a",
        warning: "#b37400",
        danger: "#c93636",
      },
      typography: {
        headingFont: "Inter",
        bodyFont: "Inter",
        headingWeight: "600",
        bodyWeight: "400",
        baseFontSize: "15px",
        lineHeight: "1.65",
        letterSpacing: "-0.011em",
      },
      spacing: {
        sectionPadding: "6rem 0",
        containerWidth: "76rem",
        cardGap: "1.5rem",
        gridGap: "1.5rem",
        buttonPadding: "0.75rem 2rem",
        inputPadding: "0.75rem 1rem",
      },
      radius: {
        buttons: "9999px",
        cards: "12px",
        inputs: "12px",
        pills: "9999px",
        images: "12px",
      },
      layout: {
        heroStyle: "default",
        contentDensity: "spacious",
        sectionSpacing: "6rem",
        navbarStyle: "solid",
      },
      effects: {
        hoverIntensity: 0.5,
        imageHoverZoom: 1.02,
        cardLift: "-1px",
        glassmorphism: false,
      },
    },
  },
  {
    id: "editorial",
    name: "Editorial",
    description: "Tipografía protagonista, ritmo contemplativo, estética de revista.",
    variant: "light",
    tokens: {
      colors: {
        primary: "#1a1a1a",
        secondary: "#faf8f5",
        accent: "#8b6914",
        background: "#fdfcfa",
        surface: "#f5f3f0",
        text: "#1a1a1a",
        muted: "#6b6560",
        border: "rgba(26, 26, 26, 0.10)",
        success: "#15956a",
        warning: "#b37400",
        danger: "#c93636",
      },
      typography: {
        headingFont: "Editorial Serif",
        bodyFont: "Inter",
        headingWeight: "700",
        bodyWeight: "400",
        baseFontSize: "16px",
        lineHeight: "1.7",
        letterSpacing: "-0.005em",
      },
      spacing: {
        sectionPadding: "7rem 0",
        containerWidth: "72rem",
        cardGap: "2rem",
        gridGap: "2rem",
        buttonPadding: "0.875rem 2.5rem",
        inputPadding: "0.875rem 1.25rem",
      },
      radius: {
        buttons: "4px",
        cards: "8px",
        inputs: "8px",
        pills: "9999px",
        images: "4px",
      },
      layout: {
        heroStyle: "centered",
        contentDensity: "spacious",
        sectionSpacing: "7rem",
        navbarStyle: "solid",
      },
      effects: {
        hoverIntensity: 0.4,
        imageHoverZoom: 1.02,
        cardLift: "-1px",
        glassmorphism: false,
      },
    },
  },
  {
    id: "bold",
    name: "Bold",
    description: "Alto contraste, CTAs agresivas, conversión directa.",
    variant: "light",
    tokens: {
      colors: {
        primary: "#000000",
        secondary: "#FFCC00",
        accent: "#FFCC00",
        background: "#ffffff",
        surface: "#f5f5f5",
        text: "#000000",
        muted: "#525252",
        border: "rgba(0, 0, 0, 0.12)",
        success: "#16a34a",
        warning: "#ca8a04",
        danger: "#dc2626",
      },
      typography: {
        headingFont: "System",
        bodyFont: "System",
        headingWeight: "800",
        bodyWeight: "400",
        baseFontSize: "15px",
        lineHeight: "1.55",
        letterSpacing: "-0.02em",
      },
      spacing: {
        sectionPadding: "4.5rem 0",
        containerWidth: "82rem",
        cardGap: "1.25rem",
        gridGap: "1.25rem",
        buttonPadding: "0.875rem 2.5rem",
        inputPadding: "0.75rem 1rem",
      },
      radius: {
        buttons: "6px",
        cards: "8px",
        inputs: "6px",
        pills: "9999px",
        images: "8px",
      },
      layout: {
        heroStyle: "default",
        contentDensity: "comfortable",
        sectionSpacing: "4.5rem",
        navbarStyle: "solid",
      },
      effects: {
        hoverIntensity: 0.9,
        imageHoverZoom: 1.05,
        cardLift: "-3px",
        glassmorphism: false,
      },
    },
  },
  {
    id: "luxury",
    name: "Luxury",
    description: "Espaciado generoso, paleta oscura, presencia aspiracional.",
    variant: "light",
    tokens: {
      colors: {
        primary: "#1c1917",
        secondary: "#f5f0eb",
        accent: "#92744a",
        background: "#faf9f7",
        surface: "#f0ece6",
        text: "#1c1917",
        muted: "#78716c",
        border: "rgba(28, 25, 23, 0.08)",
        success: "#15803d",
        warning: "#a16207",
        danger: "#b91c1c",
      },
      typography: {
        headingFont: "Editorial Serif",
        bodyFont: "Inter",
        headingWeight: "600",
        bodyWeight: "400",
        baseFontSize: "16px",
        lineHeight: "1.7",
        letterSpacing: "-0.005em",
      },
      spacing: {
        sectionPadding: "7rem 0",
        containerWidth: "72rem",
        cardGap: "2rem",
        gridGap: "2rem",
        buttonPadding: "1rem 3rem",
        inputPadding: "1rem 1.25rem",
      },
      radius: {
        buttons: "2px",
        cards: "4px",
        inputs: "4px",
        pills: "9999px",
        images: "4px",
      },
      layout: {
        heroStyle: "centered",
        contentDensity: "spacious",
        sectionSpacing: "7rem",
        navbarStyle: "solid",
      },
      effects: {
        hoverIntensity: 0.3,
        imageHoverZoom: 1.02,
        cardLift: "-1px",
        glassmorphism: false,
      },
    },
  },
  {
    id: "modern",
    name: "Modern",
    description: "Geométrico, limpio, ritmo equilibrado.",
    variant: "light",
    tokens: {
      colors: {
        primary: "#111827",
        secondary: "#f3f4f6",
        accent: "#4f46e5",
        background: "#ffffff",
        surface: "#f9fafb",
        text: "#111827",
        muted: "#6b7280",
        border: "rgba(17, 24, 39, 0.10)",
        success: "#059669",
        warning: "#d97706",
        danger: "#dc2626",
      },
      typography: {
        headingFont: "Inter",
        bodyFont: "Inter",
        headingWeight: "700",
        bodyWeight: "400",
        baseFontSize: "15px",
        lineHeight: "1.6",
        letterSpacing: "-0.015em",
      },
      spacing: {
        sectionPadding: "5rem 0",
        containerWidth: "80rem",
        cardGap: "1.5rem",
        gridGap: "1.5rem",
        buttonPadding: "0.75rem 2rem",
        inputPadding: "0.75rem 1rem",
      },
      radius: {
        buttons: "10px",
        cards: "16px",
        inputs: "10px",
        pills: "9999px",
        images: "16px",
      },
      layout: {
        heroStyle: "default",
        contentDensity: "comfortable",
        sectionSpacing: "5rem",
        navbarStyle: "solid",
      },
      effects: {
        hoverIntensity: 0.7,
        imageHoverZoom: 1.03,
        cardLift: "-2px",
        glassmorphism: false,
      },
    },
  },
  {
    id: "compact",
    name: "Compact",
    description: "Máxima densidad de contenido, ideal para catálogos grandes.",
    variant: "light",
    tokens: {
      colors: {
        primary: "#0f172a",
        secondary: "#e2e8f0",
        accent: "#2563eb",
        background: "#ffffff",
        surface: "#f8fafc",
        text: "#0f172a",
        muted: "#64748b",
        border: "rgba(15, 23, 42, 0.12)",
        success: "#15956a",
        warning: "#b37400",
        danger: "#c93636",
      },
      typography: {
        headingFont: "System",
        bodyFont: "System",
        headingWeight: "600",
        bodyWeight: "400",
        baseFontSize: "14px",
        lineHeight: "1.5",
        letterSpacing: "-0.01em",
      },
      spacing: {
        sectionPadding: "3rem 0",
        containerWidth: "84rem",
        cardGap: "1rem",
        gridGap: "1rem",
        buttonPadding: "0.625rem 1.5rem",
        inputPadding: "0.625rem 0.875rem",
      },
      radius: {
        buttons: "6px",
        cards: "8px",
        inputs: "6px",
        pills: "9999px",
        images: "8px",
      },
      layout: {
        heroStyle: "default",
        contentDensity: "compact",
        sectionSpacing: "3rem",
        navbarStyle: "solid",
      },
      effects: {
        hoverIntensity: 0.8,
        imageHoverZoom: 1.04,
        cardLift: "-2px",
        glassmorphism: false,
      },
    },
  },
  {
    id: "spacious",
    name: "Spacious",
    description: "Mucho aire, lectura sin fricción, ideal para marcas con pocas SKU.",
    variant: "light",
    tokens: {
      colors: {
        primary: "#18181b",
        secondary: "#fafafa",
        accent: "#3f4f9a",
        background: "#ffffff",
        surface: "#fafafa",
        text: "#18181b",
        muted: "#71717a",
        border: "rgba(24, 24, 27, 0.08)",
        success: "#15956a",
        warning: "#b37400",
        danger: "#c93636",
      },
      typography: {
        headingFont: "Inter",
        bodyFont: "Inter",
        headingWeight: "600",
        bodyWeight: "400",
        baseFontSize: "16px",
        lineHeight: "1.75",
        letterSpacing: "-0.01em",
      },
      spacing: {
        sectionPadding: "8rem 0",
        containerWidth: "72rem",
        cardGap: "2.5rem",
        gridGap: "2rem",
        buttonPadding: "1rem 2.5rem",
        inputPadding: "1rem 1.25rem",
      },
      radius: {
        buttons: "9999px",
        cards: "16px",
        inputs: "12px",
        pills: "9999px",
        images: "16px",
      },
      layout: {
        heroStyle: "centered",
        contentDensity: "spacious",
        sectionSpacing: "8rem",
        navbarStyle: "solid",
      },
      effects: {
        hoverIntensity: 0.4,
        imageHoverZoom: 1.02,
        cardLift: "-1px",
        glassmorphism: false,
      },
    },
  },
  {
    id: "warm",
    name: "Warm",
    description: "Tonos cálidos, bordes suaves, sensación acogedora.",
    variant: "light",
    tokens: {
      colors: {
        primary: "#3a2e29",
        secondary: "#fdf2e9",
        accent: "#c2410c",
        background: "#fffbf7",
        surface: "#fef7f0",
        text: "#3a2e29",
        muted: "#8c7a72",
        border: "rgba(58, 46, 41, 0.10)",
        success: "#16a34a",
        warning: "#ca8a04",
        danger: "#dc2626",
      },
      typography: {
        headingFont: "Rounded Commerce",
        bodyFont: "Inter",
        headingWeight: "700",
        bodyWeight: "400",
        baseFontSize: "15px",
        lineHeight: "1.65",
        letterSpacing: "-0.01em",
      },
      spacing: {
        sectionPadding: "5.5rem 0",
        containerWidth: "76rem",
        cardGap: "1.5rem",
        gridGap: "1.5rem",
        buttonPadding: "0.875rem 2rem",
        inputPadding: "0.875rem 1rem",
      },
      radius: {
        buttons: "12px",
        cards: "16px",
        inputs: "12px",
        pills: "9999px",
        images: "16px",
      },
      layout: {
        heroStyle: "default",
        contentDensity: "comfortable",
        sectionSpacing: "5.5rem",
        navbarStyle: "solid",
      },
      effects: {
        hoverIntensity: 0.6,
        imageHoverZoom: 1.03,
        cardLift: "-2px",
        glassmorphism: false,
      },
    },
  },
  {
    id: "dark-commerce",
    name: "Dark Commerce",
    description: "Fondo oscuro real, texto claro, CTAs brillantes.",
    variant: "dark",
    tokens: {
      colors: {
        primary: "#ffffff",
        secondary: "#18181b",
        accent: "#a78bfa",
        background: "#09090b",
        surface: "#18181b",
        text: "#fafafa",
        muted: "#a1a1aa",
        border: "rgba(255, 255, 255, 0.10)",
        success: "#4ade80",
        warning: "#fbbf24",
        danger: "#f87171",
      },
      typography: {
        headingFont: "Inter",
        bodyFont: "Inter",
        headingWeight: "700",
        bodyWeight: "400",
        baseFontSize: "15px",
        lineHeight: "1.6",
        letterSpacing: "-0.015em",
      },
      spacing: {
        sectionPadding: "5rem 0",
        containerWidth: "80rem",
        cardGap: "1.5rem",
        gridGap: "1.5rem",
        buttonPadding: "0.75rem 2rem",
        inputPadding: "0.75rem 1rem",
      },
      radius: {
        buttons: "8px",
        cards: "12px",
        inputs: "8px",
        pills: "9999px",
        images: "12px",
      },
      shadows: {
        cards:
          "0 1px 2px rgba(0,0,0,0.3), 0 4px 12px -2px rgba(0,0,0,0.4)",
        dropdowns:
          "0 4px 16px rgba(0,0,0,0.5), 0 16px 32px -8px rgba(0,0,0,0.4)",
        modals:
          "0 4px 16px rgba(0,0,0,0.5), 0 16px 32px -8px rgba(0,0,0,0.4)",
        elevated:
          "0 2px 4px rgba(0,0,0,0.3), 0 10px 24px -4px rgba(0,0,0,0.5)",
      },
      layout: {
        heroStyle: "default",
        contentDensity: "comfortable",
        sectionSpacing: "5rem",
        navbarStyle: "solid",
      },
      effects: {
        hoverIntensity: 0.8,
        imageHoverZoom: 1.04,
        cardLift: "-2px",
        glassmorphism: true,
      },
    },
  },
];

export function findPresetById(id: string): ThemePreset | null {
  return THEME_PRESETS.find((p) => p.id === id) ?? null;
}
